classdef ModelConstants
    
    properties (Constant)
        
        MuscleList = ...
           {'digastric_post','digastric_post_L', ...        % (1,2)
            'digastric_ant','digastric_ant_L', ...          % (3,4)           
            'mylohyoid_ant','mylohyoid_ant_L', ...          % (5,6)            
            'stylohyoid_lat','stylohyoid_lat_L', ...        % (7,8)
            'stylohyoid_med','stylohyoid_med_L', ...        % (9,10)
            'sternohyoid','sternohyoid_L', ...              % (11,12)
            'geniohyoid','geniohyoid_L', ...                % (13,14)
            'mylohyoid_post','mylohyoid_post_L', ...        % (15,16)
            'sternothyroid','sternothyroid_L', ...          % (17,18)
            'omohyoid', 'omohyoid_L', ...                   % (19,20)
            'stern_mast','stern_mast_L', ...                % (21,22)
            'cleid_mast','cleid_mast_L',...                 % (23,24)
            'cleid_occ','cleid_occ_L', ...                  % (25,26)
            'scalenus_ant','scalenus_ant_L',...             % (27,28)
            'scalenus_med','scalenus_med_L', ...            % (29,30)
            'scalenus_post','scalenus_post_L',...           % (31,32)
            'long_cap_sklc4','long_cap_sklc4_L', ...        % (33,34)
            'long_col_c1thx','long_col_c1thx_L',...         % (35,36)
            'long_col_c1c5','long_col_c1c5_L', ...          % (37,38)
            'long_col_c5thx','long_col_c5thx_L',...         % (39,40)
            'trap_cl','trap_cl_L', ...                      % (41,42)
            'trap_acr','trap_acr_L',...                     % (43,44)
            'splen_cap_sklc6','splen_cap_sklc6_L', ...      % (45,46)
            'splen_cap_sklthx','splen_cap_sklthx_L',...     % (47,48)
            'semi_cap_sklc5','semi_cap_sklc5_L', ...        % (49,50)
            'semi_cap_sklthx','semi_cap_sklthx_L', ...      % (51,52)
            'splen_cerv_c3thx','splen_cerv_c3thx_L', ...    % (53,54)
            'semi_cerv_c3thx','semi_cerv_c3thx_L', ...      % (55,56)
            'levator_scap','levator_scap_L', ...            % (57,58)
            'longissi_cap_sklc6','longissi_cap_sklc6_L', ...% (59,60)
            'longissi_cerv_c4thx','longissi_cerv_c4thx_L', ...%(61,62)
            'iliocost_cerv_c5rib','iliocost_cerv_c5rib_L', ...%(63,64)
            'rectcap_post_maj','rectcap_post_maj_L', ...    % (65,66)
            'rectcap_post_min','rectcap_post_min_L', ...    % (67,68)
            'obl_cap_sup','obl_cap_sup_L', ...              % (69,70)
            'obl_cap_inf','obl_cap_inf_L', ...              % (71,72)
            'mult_sup_C45C2','mult_sup_C45C2_L', ...        % (73,74)
            'mult_sup_C56C2','mult_sup_C56C2_L', ...        % (75,76)
            'mult_sup_C67C2','mult_sup_C67C2_L', ...        % (77,78)
            'mult_sup_T1C4','mult_sup_T1C4_L', ...          % (79,80)
            'mult_sup_T1C5','mult_sup_T1C5_L', ...          % (81,82)
            'mult_sup_T2C6','mult_sup_T2C6_L', ...          % (83,84)
            'mult_deep_C45C2','mult_deep_C45C2_L', ...      % (85,86)
            'mult_deep_C56C3','mult_deep_C56C3_L', ...      % (87,88)
            'mult_deep_C67C4','mult_deep_C67C4_L', ...      % (89,90)
            'mult_deep_T1C5','mult_deep_T1C5_L', ...        % (91,92)
            'mult_deep_T1C6','mult_deep_T1C6_L', ...        % (93,94)
            'mult_deep_T2C7','mult_deep_T2C7_L'};           % (95,96)

        
        MuscleList_reduced = ...
            {'stern_mast','stern_mast_L', ...
            'cleid_mast','cleid_mast_L',...
            'cleid_occ','cleid_occ_L', ...
            'scalenus_ant','scalenus_ant_L',...
            'scalenus_med','scalenus_med_L', ...
            'scalenus_post','scalenus_post_L',...
            'long_cap_sklc4','long_cap_sklc4_L', ...
            'long_col_c1thx','long_col_c1thx_L',...
            'long_col_c1c5','long_col_c1c5_L', ...
            'long_col_c5thx','long_col_c5thx_L',...
            'trap_cl','trap_cl_L', ...
            'trap_acr','trap_acr_L',...
            'splen_cap_sklc6','splen_cap_sklc6_L', ...
            'splen_cap_sklthx','splen_cap_sklthx_L',...
            'semi_cap_sklc5','semi_cap_sklc5_L', ...
            'semi_cap_sklthx','semi_cap_sklthx_L', ...
            'splen_cerv_c3thx','splen_cerv_c3thx_L', ...
            'semi_cerv_c3thx','semi_cerv_c3thx_L', ...
            'levator_scap','levator_scap_L', ...
            'longissi_cap_sklc6','longissi_cap_sklc6_L', ...
            'longissi_cerv_c4thx','longissi_cerv_c4thx_L', ...
            'iliocost_cerv_c5rib','iliocost_cerv_c5rib_L', ...
            'rectcap_post_maj','rectcap_post_maj_L', ...
            'obl_cap_inf','obl_cap_inf_L', ...
            'mult_sup_C45C2','mult_sup_C45C2_L', ...
            'mult_sup_C56C2','mult_sup_C56C2_L', ...
            'mult_sup_C67C2','mult_sup_C67C2_L', ...
            'mult_sup_T1C5','mult_sup_T1C5_L', ...
            'mult_sup_T2C6','mult_sup_T2C6_L', ...
            'mult_deep_C45C2','mult_deep_C45C2_L', ...
            'mult_deep_C56C3','mult_deep_C56C3_L', ...
            'mult_deep_C67C4','mult_deep_C67C4_L', ...
            'mult_deep_T1C5','mult_deep_T1C5_L', ...
            'mult_deep_T1C6','mult_deep_T1C6_L', ...
            'mult_deep_T2C7','mult_deep_T2C7_L', ...
            }; %70 muscles; multif: 58-70
        
        CoordList = ...
           {'pitch8', 'roll8', 'yaw8', ...
            'pitch7', 'roll7', 'yaw7', ...
            'pitch6', 'roll6', 'yaw6', ...
            'pitch5', 'roll5', 'yaw5', ...
            'pitch4', 'roll4', 'yaw4', ...
            'pitch3', 'roll3', 'yaw3', ...
            'pitch2', 'roll2', 'yaw2', ...
            'pitch1', 'roll1', 'yaw1'}
            
       
        CoordList24 = ...
            {'pitch2', 'roll2', 'yaw2', ...
            'aux7jnt_r3', 'aux7jnt_r1', 'aux7jnt_r2', ...
            'aux6jnt_r3', 'aux6jnt_r1', 'aux6jnt_r2', ...
            'aux5jnt_r3', 'aux5jnt_r1', 'aux5jnt_r2', ...
            'aux4jnt_r3', 'aux4jnt_r1', 'aux4jnt_r2', ...
            'aux3jnt_r3', 'aux3jnt_r1', 'aux3jnt_r2', ...
            'pitch1', 'roll1', 'yaw1', ...
            'aux1jnt_r3', 'aux1jnt_r1', 'aux1jnt_r2' }; %24 coordinates indexed in this order
        
        CoordList6 = ...
            {'pitch2', 'roll2', 'yaw2', ...
            'pitch1', 'roll1', 'yaw1'};
        
        CoordList9 = ...
            {'pitch3', 'roll3', 'yaw3', ...
            'pitch2', 'roll2', 'yaw2', ...
            'pitch1', 'roll1', 'yaw1'};
        
        CoordListKuo = ...
            {'pitch7', 'roll7', 'yaw7', ...
            'pitch6', 'roll6', 'yaw6', ...
            'pitch5', 'roll5', 'yaw5', ...
            'pitch4', 'roll4', 'yaw4', ...
            'pitch3', 'roll3', 'yaw3', ...
            'pitch2', 'roll2', 'yaw2', ...
            'yaw1', 'skullpitch'}; %20. note last 2 coords
        
        BushingForceList = ...
        {'Spine_C7_Bushing', ...
         'C7_C6_Bushing', ...
         'C6_C5_Bushing',...
         'C5_C4_Bushing', ...
         'C4_C3_Bushing', ...
         'C3_C2_Bushing', ...
         'C2_C1_Bushing', ...
         'C1_skull_Bushing'};
        
        BushingForceList_reduced = ...
            {'Spine_C7_Bushing',...
            'C5_C4_Bushing',...
            'C1_skull_Bushing'};
        
        NeckJointList = ...
           {'spine_0', ...
            'C7T1jnt', ...
            'C6C7jnt', ...
            'C5C6jnt', ...
            'C4C5jnt', ...
            'C3C4jnt', ...
            'C2C3jnt', ...
            'C1C2jnt', ...
            'C0C1jnt'};
        
%         %postures.mat must have 9 columns indexed by the following: 
%         IndCoords = ...
%             {'gndpitch','gndroll','gndyaw', ...
%             'pitch2','roll2','yaw2',...
%             'pitch1','roll1','yaw1'}; %(9) leaving out spine_t*
        
        Coords_LB_rad = ...
            [ -pi(), -pi(), -pi(), ...
            -0.576, -0.576, -0.471, ... 
            -0.279, -0.105, -0.663 ]; % radians
        
        Coords_LB_deg = ...
            [ -180, -180, -180,  ...
            -33,  -33,  -27, ...
            -16,   -6,  -38 ]; % degrees
        
        Coords_UB_rad = ...
            [ pi(), pi(), pi(), ...
            0.837, 0.575, 0.471, ...
            0.419, 0.104, 0.663 ]; % radians
        
        Coords_UB_deg = ...
            [ 180,  180,  180,   ...
            48,   33,   27, ...
            24,    6,   38 ]; % degrees
                    
        % % Curves that define force-length relationship, directly from muscle model: Shutte 1993
        % "tendon_force_length_curve" and "active/passive force_velocity_curve" not needed for static, rigid tendon
        
        % afl "active_force_length_curve"
        afl = [[-5 0 0.401 0.402 0.4035 0.52725 0.62875 0.71875 0.86125 1 1.045 1.2175 1.43875 1.61875 1.62 1.621 2.2 5];...
               [0 0 0 0 0 0.226667 0.636667 0.856667 0.95 1 0.993333 0.77 0.246667 0 0 0 0 0]]';
        
        %pfl "passive force length curve"   
        pfl = [[-5 0 1 1.05 1.1 1.125 1.14 1.145 1.15 1.25 1.35 1.45 1.55 1.65 1.75 1.7501 1.7502 5];...
                [0 0 0 0 0 0 0 0 0 0.035 0.12 0.26 0.55 1.17 2 2 2 2]]';
          
    
    end
    
end
        